
try:
    print "no exception"
finally:
    print "done"
